### ISSUE TITLE
“404 page not found”

### ISSUE THREAD

**Issue by da2x** [multiformats/cid-utils-website#11]
The http://cid-utils.ipfs.team/ website returns 404 Not Found.

**Comment by mkmik** [comment]
fwiw I published and pinned the current master, accessible at: https://ipfs.io/ipfs/QmcTu41GC2jHs5qeJewTiWJVMCRdvX6HXsTiW4ruj8dktS

**Comment by lidel** [comment]
cc  https://github.com/protocol/infra/issues/382

**Comment by olizilla** [comment]
This is now available at https://cid.ipfs.io

**Comment by lidel** [comment]
@olizilla would it make sense to compliment this with HTTP 301 from https://cid-utils.ipfs.team  to https://cid.ipfs.io/? I suspect the old URL is still listed in various issues & videos.

**Comment by olizilla** [comment]
Would be great, but I don't think infra have access to that domain.

**Comment by lidel** [comment]
Do we know who does? (:
