### ISSUE TITLE
Codec showing varint instead of code

### ISSUE THREAD

**Issue by austinabell** [multiformats/cid-utils-website#21]
for reference:

https://cid.ipfs.io/#baguqeeranycvebnhdwjwaimaylo2lon5h22ueqdto74e5wnfnm7rspq4or7q

shows code is `0xa902` where the actual JSON code is `0x0129`. The former is the varint encoding of the latter, but misleading because it's the wrong code and isn't decoded

**Comment by lidel** [comment]
@austinabell would you be interested in submitting PR with a fix?

**Comment by austinabell** [comment]
> @austinabell would you be interested in submitting PR with a fix?

No, sorry. I don't need for any reason
