### ISSUE TITLE
Support Base36

### ISSUE THREAD

**Issue by lidel** [multiformats/cid-utils-website#23]
Problem: 
- https://cid.ipfs.io/#k2cwueckqkibutvhkr4p2ln2pjcaxaakpd9db0e7j7ax1lxhhxy3ekpv
- https://cid.ipfs.io/#k51qzi5uqu5dj16qyiq0tajolkojyl9qdkr254920wxv7ghtuwcz593tp69z9m (inlined ED25519)

Context:
- https://github.com/ipfs/go-cid/pull/107
- https://github.com/ipfs/go-ipfs/issues/7318

**Comment by ribasushi** [comment]
@hugomrdias flag @lidel when the b36 support lands in js-land
