### ISSUE TITLE
Add a link to this repo

### ISSUE THREAD

**Issue by vmx** [multiformats/cid-utils-website#27]
Link to this repo from the tool itself so that people can open issues if things don't work as expected or if they have ideas for improvements.

**Comment by terichadbourne** [comment]
Great idea, @vmx. What would you think of doing as a GitHub logo added to this row at the bottom? 

![image](https://user-images.githubusercontent.com/19171465/87988243-01b54a80-caae-11ea-93cf-8c3d9efc42a6.png)

**Comment by vmx** [comment]
Sounds good to me.

**Comment by lidel** [comment]
prior art:  https://ipfs.github.io/public-gateway-checker/ and https://explore.ipld.io/ have github icon in the header that points to the repo:

> ![2020-07-21--13-19-08](https://user-images.githubusercontent.com/157609/88049098-c752b880-cb54-11ea-918d-2fff637c05aa.png)

**Comment by jessicaschilling** [comment]
https://github.com/multiformats/cid-utils-website/pull/30 closes this.
