### ISSUE TITLE
Add tool for converting cidv0s to cidv1s and back

### ISSUE THREAD

**Issue by olizilla** [multiformats/cid-utils-website#4]

**Comment by lgierth** [comment]
It'd be useful to just print the base32 CIDv0 just like the base32 CIDv1. (The result is basically bafy=>baby).

**Comment by lidel** [comment]
I think this can be closed as cidv1b32 was added in https://github.com/ipfs/cid-utils-website/pull/8, yes?
http://cid-utils.ipfs.team/#QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR
