### ISSUE TITLE
Can't decode emoji CIDs

### ISSUE THREAD

**Issue by olizilla** [multiformats/cid-utils-website#44]
Similar problem as #43. IPFS now supports emoji CIDs adn cid.ipfs.io does not.

example from @ribasushi
https://cid.ipfs.io/#🚀🪐⭐💻😅❓💎🌈🌸🌚💰💍🌒😵🐶💁🤐🌎👼🙃🙅☺🌚😞🤤⭐🚀😃✈🌕😚🍻💜🐷⚽✌😊

The main blocker here is that to fix it the guts of the site will have to be rewritten to use the [new multiformats lib](https://github.com/multiformats/js-multiformats/)

**Comment by hacdias** [comment]
The website seems relatively simple so I'll be glad to take this one on. Good opportunity to check how the new multiformats lib works.

**Comment by lidel** [comment]
https://cid.ipfs.io/#%F0%9F%9A%80%F0%9F%AA%90%E2%AD%90%F0%9F%92%BB%F0%9F%98%85%E2%9D%93%F0%9F%92%8E%F0%9F%8C%88%F0%9F%8C%B8%F0%9F%8C%9A%F0%9F%92%B0%F0%9F%92%8D%F0%9F%8C%92%F0%9F%98%B5%F0%9F%90%B6%F0%9F%92%81%F0%9F%A4%90%F0%9F%8C%8E%F0%9F%91%BC%F0%9F%99%83%F0%9F%99%85%E2%98%BA%F0%9F%8C%9A%F0%9F%98%9E%F0%9F%A4%A4%E2%AD%90%F0%9F%9A%80%F0%9F%98%83%E2%9C%88%F0%9F%8C%95%F0%9F%98%9A%F0%9F%8D%BB%F0%9F%92%9C%F0%9F%90%B7%E2%9A%BD%E2%9C%8C%F0%9F%98%8A is a reality 

![slow-heavy-metal](https://user-images.githubusercontent.com/157609/182210376-442bc764-a7b4-4a1f-976f-09ff4de2819f.jpg)
